<?php
/**
 * IoColorsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PkIo;

/**
 * IoColorsTest Class Doc Comment
 *
 * @category    Class
 * @description Colours take a hexcode input.  A &#x27;#&#x27; prefix is optional.
 * @package     PkIo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IoColorsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IoColors"
     */
    public function testIoColors()
    {
    }

    /**
     * Test attribute "backgroundColor"
     */
    public function testPropertyBackgroundColor()
    {
    }

    /**
     * Test attribute "labelColor"
     */
    public function testPropertyLabelColor()
    {
    }

    /**
     * Test attribute "textColor"
     */
    public function testPropertyTextColor()
    {
    }

    /**
     * Test attribute "stripColor"
     */
    public function testPropertyStripColor()
    {
    }
}
