<?php
/**
 * IoEmailTemplateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PkIo;

/**
 * IoEmailTemplateTest Class Doc Comment
 *
 * @category    Class
 * @description IoEmailTemplate
 * @package     PkIo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IoEmailTemplateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IoEmailTemplate"
     */
    public function testIoEmailTemplate()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "localizedSubject"
     */
    public function testPropertyLocalizedSubject()
    {
    }

    /**
     * Test attribute "bodyTextContent"
     */
    public function testPropertyBodyTextContent()
    {
    }

    /**
     * Test attribute "localizedBodyTextContent"
     */
    public function testPropertyLocalizedBodyTextContent()
    {
    }

    /**
     * Test attribute "bodyHtmlContent"
     */
    public function testPropertyBodyHtmlContent()
    {
    }

    /**
     * Test attribute "localizedBodyHtmlContent"
     */
    public function testPropertyLocalizedBodyHtmlContent()
    {
    }

    /**
     * Test attribute "configuration"
     */
    public function testPropertyConfiguration()
    {
    }

    /**
     * Test attribute "buttonText"
     */
    public function testPropertyButtonText()
    {
    }

    /**
     * Test attribute "buttonTextColor"
     */
    public function testPropertyButtonTextColor()
    {
    }

    /**
     * Test attribute "buttonBackgroundColor"
     */
    public function testPropertyButtonBackgroundColor()
    {
    }

    /**
     * Test attribute "buttonBorderRadius"
     */
    public function testPropertyButtonBorderRadius()
    {
    }

    /**
     * Test attribute "footerTextContent"
     */
    public function testPropertyFooterTextContent()
    {
    }

    /**
     * Test attribute "localizedFooterTextContent"
     */
    public function testPropertyLocalizedFooterTextContent()
    {
    }

    /**
     * Test attribute "footerHtmlContent"
     */
    public function testPropertyFooterHtmlContent()
    {
    }

    /**
     * Test attribute "localizedFooterHtmlContent"
     */
    public function testPropertyLocalizedFooterHtmlContent()
    {
    }

    /**
     * Test attribute "messageBackgroundColor"
     */
    public function testPropertyMessageBackgroundColor()
    {
    }

    /**
     * Test attribute "pageBackgroundColor"
     */
    public function testPropertyPageBackgroundColor()
    {
    }
}
