<?php
/**
 * IoImageDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PkIo;

/**
 * IoImageDataTest Class Doc Comment
 *
 * @category    Class
 * @description Image data can be provided as either a url or base 64 encoded data.
 * @package     PkIo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IoImageDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IoImageData"
     */
    public function testIoImageData()
    {
    }

    /**
     * Test attribute "icon"
     */
    public function testPropertyIcon()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "appleLogo"
     */
    public function testPropertyAppleLogo()
    {
    }

    /**
     * Test attribute "hero"
     */
    public function testPropertyHero()
    {
    }

    /**
     * Test attribute "eventStrip"
     */
    public function testPropertyEventStrip()
    {
    }

    /**
     * Test attribute "strip"
     */
    public function testPropertyStrip()
    {
    }

    /**
     * Test attribute "thumbnail"
     */
    public function testPropertyThumbnail()
    {
    }

    /**
     * Test attribute "background"
     */
    public function testPropertyBackground()
    {
    }

    /**
     * Test attribute "footer"
     */
    public function testPropertyFooter()
    {
    }

    /**
     * Test attribute "security"
     */
    public function testPropertySecurity()
    {
    }

    /**
     * Test attribute "privilege"
     */
    public function testPropertyPrivilege()
    {
    }

    /**
     * Test attribute "airlineAlliance"
     */
    public function testPropertyAirlineAlliance()
    {
    }

    /**
     * Test attribute "personalization"
     */
    public function testPropertyPersonalization()
    {
    }

    /**
     * Test attribute "banner"
     */
    public function testPropertyBanner()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {
    }

    /**
     * Test attribute "appImage"
     */
    public function testPropertyAppImage()
    {
    }

    /**
     * Test attribute "localizedIcon"
     */
    public function testPropertyLocalizedIcon()
    {
    }

    /**
     * Test attribute "localizedLogo"
     */
    public function testPropertyLocalizedLogo()
    {
    }

    /**
     * Test attribute "localizedAppleLogo"
     */
    public function testPropertyLocalizedAppleLogo()
    {
    }

    /**
     * Test attribute "localizedHero"
     */
    public function testPropertyLocalizedHero()
    {
    }

    /**
     * Test attribute "localizedEventStrip"
     */
    public function testPropertyLocalizedEventStrip()
    {
    }

    /**
     * Test attribute "localizedStrip"
     */
    public function testPropertyLocalizedStrip()
    {
    }

    /**
     * Test attribute "localizedThumbnail"
     */
    public function testPropertyLocalizedThumbnail()
    {
    }

    /**
     * Test attribute "localizedBackground"
     */
    public function testPropertyLocalizedBackground()
    {
    }

    /**
     * Test attribute "localizedFooter"
     */
    public function testPropertyLocalizedFooter()
    {
    }

    /**
     * Test attribute "localizedSecurity"
     */
    public function testPropertyLocalizedSecurity()
    {
    }

    /**
     * Test attribute "localizedPrivilege"
     */
    public function testPropertyLocalizedPrivilege()
    {
    }

    /**
     * Test attribute "localizedAirlineAlliance"
     */
    public function testPropertyLocalizedAirlineAlliance()
    {
    }

    /**
     * Test attribute "localizedPersonalization"
     */
    public function testPropertyLocalizedPersonalization()
    {
    }

    /**
     * Test attribute "localizedBanner"
     */
    public function testPropertyLocalizedBanner()
    {
    }

    /**
     * Test attribute "localizedMessage"
     */
    public function testPropertyLocalizedMessage()
    {
    }
}
