<?php
/**
 * IoImageIdsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PkIo;

/**
 * IoImageIdsTest Class Doc Comment
 *
 * @category    Class
 * @description This manages images by id
 * @package     PkIo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IoImageIdsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IoImageIds"
     */
    public function testIoImageIds()
    {
    }

    /**
     * Test attribute "icon"
     */
    public function testPropertyIcon()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "appleLogo"
     */
    public function testPropertyAppleLogo()
    {
    }

    /**
     * Test attribute "hero"
     */
    public function testPropertyHero()
    {
    }

    /**
     * Test attribute "eventStrip"
     */
    public function testPropertyEventStrip()
    {
    }

    /**
     * Test attribute "strip"
     */
    public function testPropertyStrip()
    {
    }

    /**
     * Test attribute "thumbnail"
     */
    public function testPropertyThumbnail()
    {
    }

    /**
     * Test attribute "background"
     */
    public function testPropertyBackground()
    {
    }

    /**
     * Test attribute "footer"
     */
    public function testPropertyFooter()
    {
    }

    /**
     * Test attribute "security"
     */
    public function testPropertySecurity()
    {
    }

    /**
     * Test attribute "privilege"
     */
    public function testPropertyPrivilege()
    {
    }

    /**
     * Test attribute "airlineAlliance"
     */
    public function testPropertyAirlineAlliance()
    {
    }

    /**
     * Test attribute "personalization"
     */
    public function testPropertyPersonalization()
    {
    }

    /**
     * Test attribute "banner"
     */
    public function testPropertyBanner()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {
    }

    /**
     * Test attribute "appImage"
     */
    public function testPropertyAppImage()
    {
    }
}
