<?php
/**
 * IoPersonTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PkIo;

/**
 * IoPersonTest Class Doc Comment
 *
 * @category    Class
 * @description A person represents a single, identifiable individual.
 * @package     PkIo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IoPersonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IoPerson"
     */
    public function testIoPerson()
    {
    }

    /**
     * Test attribute "surname"
     */
    public function testPropertySurname()
    {
    }

    /**
     * Test attribute "forename"
     */
    public function testPropertyForename()
    {
    }

    /**
     * Test attribute "otherNames"
     */
    public function testPropertyOtherNames()
    {
    }

    /**
     * Test attribute "salutation"
     */
    public function testPropertySalutation()
    {
    }

    /**
     * Test attribute "suffix"
     */
    public function testPropertySuffix()
    {
    }

    /**
     * Test attribute "displayName"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "dateOfBirth"
     */
    public function testPropertyDateOfBirth()
    {
    }

    /**
     * Test attribute "emailAddress"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "mobileNumber"
     */
    public function testPropertyMobileNumber()
    {
    }

    /**
     * Test attribute "externalId"
     */
    public function testPropertyExternalId()
    {
    }
}
