<?php
/**
 * SingleUseCouponsStandardPassKitHostedPageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PkIo;

/**
 * SingleUseCouponsStandardPassKitHostedPageTest Class Doc Comment
 *
 * @category    Class
 * @description SingleUseCouponsStandardPassKitHostedPage
 * @package     PkIo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SingleUseCouponsStandardPassKitHostedPageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SingleUseCouponsStandardPassKitHostedPage"
     */
    public function testSingleUseCouponsStandardPassKitHostedPage()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "localizedTitle"
     */
    public function testPropertyLocalizedTitle()
    {
    }

    /**
     * Test attribute "redemptionInstructions"
     */
    public function testPropertyRedemptionInstructions()
    {
    }

    /**
     * Test attribute "localizedRedemptionInstructions"
     */
    public function testPropertyLocalizedRedemptionInstructions()
    {
    }

    /**
     * Test attribute "imageIds"
     */
    public function testPropertyImageIds()
    {
    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {
    }

    /**
     * Test attribute "footerText"
     */
    public function testPropertyFooterText()
    {
    }

    /**
     * Test attribute "localizedFooterText"
     */
    public function testPropertyLocalizedFooterText()
    {
    }

    /**
     * Test attribute "responseTexts"
     */
    public function testPropertyResponseTexts()
    {
    }

    /**
     * Test attribute "hideRedeemedDateTime"
     */
    public function testPropertyHideRedeemedDateTime()
    {
    }

    /**
     * Test attribute "callToActionButton"
     */
    public function testPropertyCallToActionButton()
    {
    }

    /**
     * Test attribute "cssOverrides"
     */
    public function testPropertyCssOverrides()
    {
    }
}
