<?php
/**
 * SingleUseCouponsRedemptionDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PkIo;

/**
 * SingleUseCouponsRedemptionDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description SingleUseCouponsRedemptionDetails
 * @package     PkIo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SingleUseCouponsRedemptionDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SingleUseCouponsRedemptionDetails"
     */
    public function testSingleUseCouponsRedemptionDetails()
    {
    }

    /**
     * Test attribute "redemptionDate"
     */
    public function testPropertyRedemptionDate()
    {
    }

    /**
     * Test attribute "redemptionCode"
     */
    public function testPropertyRedemptionCode()
    {
    }

    /**
     * Test attribute "lat"
     */
    public function testPropertyLat()
    {
    }

    /**
     * Test attribute "lon"
     */
    public function testPropertyLon()
    {
    }

    /**
     * Test attribute "alt"
     */
    public function testPropertyAlt()
    {
    }

    /**
     * Test attribute "redemptionSource"
     */
    public function testPropertyRedemptionSource()
    {
    }

    /**
     * Test attribute "redemptionReference"
     */
    public function testPropertyRedemptionReference()
    {
    }

    /**
     * Test attribute "transactionReference"
     */
    public function testPropertyTransactionReference()
    {
    }

    /**
     * Test attribute "transactionAmount"
     */
    public function testPropertyTransactionAmount()
    {
    }
}
