<?php
/**
 * SingleUseCouponsCallToActionButtonTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PkIo;

/**
 * SingleUseCouponsCallToActionButtonTest Class Doc Comment
 *
 * @category    Class
 * @description Call to action button rendered on error page of coupon already redeemed to provide better customer experience.
 * @package     PkIo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SingleUseCouponsCallToActionButtonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SingleUseCouponsCallToActionButton"
     */
    public function testSingleUseCouponsCallToActionButton()
    {
    }

    /**
     * Test attribute "hideCallToActionButton"
     */
    public function testPropertyHideCallToActionButton()
    {
    }

    /**
     * Test attribute "buttonText"
     */
    public function testPropertyButtonText()
    {
    }

    /**
     * Test attribute "localizedButtonText"
     */
    public function testPropertyLocalizedButtonText()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }

    /**
     * Test attribute "localizedLink"
     */
    public function testPropertyLocalizedLink()
    {
    }
}
