<?php
/**
 * SingleUseCouponsCouponOfferTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PkIo;

/**
 * SingleUseCouponsCouponOfferTest Class Doc Comment
 *
 * @category    Class
 * @description Holds the offer details, redemption settings and before &amp; after-redeem template designs (Apple Wallet &amp; Google Pay designs) for the Coupon Offer.
 * @package     PkIo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SingleUseCouponsCouponOfferTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SingleUseCouponsCouponOffer"
     */
    public function testSingleUseCouponsCouponOffer()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "offerTitle"
     */
    public function testPropertyOfferTitle()
    {
    }

    /**
     * Test attribute "localizedOfferTitle"
     */
    public function testPropertyLocalizedOfferTitle()
    {
    }

    /**
     * Test attribute "offerShortTitle"
     */
    public function testPropertyOfferShortTitle()
    {
    }

    /**
     * Test attribute "localizedOfferShortTitle"
     */
    public function testPropertyLocalizedOfferShortTitle()
    {
    }

    /**
     * Test attribute "offerDetails"
     */
    public function testPropertyOfferDetails()
    {
    }

    /**
     * Test attribute "localizedOfferDetails"
     */
    public function testPropertyLocalizedOfferDetails()
    {
    }

    /**
     * Test attribute "offerFinePrint"
     */
    public function testPropertyOfferFinePrint()
    {
    }

    /**
     * Test attribute "localizedOfferFinePrint"
     */
    public function testPropertyLocalizedOfferFinePrint()
    {
    }

    /**
     * Test attribute "beforeRedeemPassTemplateId"
     */
    public function testPropertyBeforeRedeemPassTemplateId()
    {
    }

    /**
     * Test attribute "afterRedeemPassTemplateId"
     */
    public function testPropertyAfterRedeemPassTemplateId()
    {
    }

    /**
     * Test attribute "quota"
     */
    public function testPropertyQuota()
    {
    }

    /**
     * Test attribute "couponExpirySettings"
     */
    public function testPropertyCouponExpirySettings()
    {
    }

    /**
     * Test attribute "redemptionSettings"
     */
    public function testPropertyRedemptionSettings()
    {
    }

    /**
     * Test attribute "issueStartDate"
     */
    public function testPropertyIssueStartDate()
    {
    }

    /**
     * Test attribute "issueEndDate"
     */
    public function testPropertyIssueEndDate()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {
    }

    /**
     * Test attribute "campaignId"
     */
    public function testPropertyCampaignId()
    {
    }

    /**
     * Test attribute "distributionSettings"
     */
    public function testPropertyDistributionSettings()
    {
    }

    /**
     * Test attribute "shortCode"
     */
    public function testPropertyShortCode()
    {
    }

    /**
     * Test attribute "ianaTimezone"
     */
    public function testPropertyIanaTimezone()
    {
    }

    /**
     * Test attribute "disabled"
     */
    public function testPropertyDisabled()
    {
    }
}
