<?php
/**
 * SingleUseCouponsResponseTextsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PkIo;

/**
 * SingleUseCouponsResponseTextsTest Class Doc Comment
 *
 * @category    Class
 * @description Customize success or error messages shown on the page or error dialog box.
 * @package     PkIo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SingleUseCouponsResponseTextsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SingleUseCouponsResponseTexts"
     */
    public function testSingleUseCouponsResponseTexts()
    {
    }

    /**
     * Test attribute "redeemConfirmationDialogBoxText"
     */
    public function testPropertyRedeemConfirmationDialogBoxText()
    {
    }

    /**
     * Test attribute "localizedRedeemConfirmationDialogBoxText"
     */
    public function testPropertyLocalizedRedeemConfirmationDialogBoxText()
    {
    }

    /**
     * Test attribute "cancelRedeemText"
     */
    public function testPropertyCancelRedeemText()
    {
    }

    /**
     * Test attribute "localizedCancelRedeemText"
     */
    public function testPropertyLocalizedCancelRedeemText()
    {
    }

    /**
     * Test attribute "afterRedeemText"
     */
    public function testPropertyAfterRedeemText()
    {
    }

    /**
     * Test attribute "localizedAfterRedeemText"
     */
    public function testPropertyLocalizedAfterRedeemText()
    {
    }

    /**
     * Test attribute "couponAlreadyRedeemedText"
     */
    public function testPropertyCouponAlreadyRedeemedText()
    {
    }

    /**
     * Test attribute "localizedCouponAlreadyRedeemedText"
     */
    public function testPropertyLocalizedCouponAlreadyRedeemedText()
    {
    }

    /**
     * Test attribute "offerExpiredText"
     */
    public function testPropertyOfferExpiredText()
    {
    }

    /**
     * Test attribute "localizedOfferExpiredText"
     */
    public function testPropertyLocalizedOfferExpiredText()
    {
    }

    /**
     * Test attribute "couponExpiredText"
     */
    public function testPropertyCouponExpiredText()
    {
    }

    /**
     * Test attribute "localizedCouponExpiredText"
     */
    public function testPropertyLocalizedCouponExpiredText()
    {
    }
}
