<?php
/**
 * CouponRESTAPIApiTest
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace PkIo;

use PkIo\Configuration;
use PkIo\ApiException;
use PkIo\ObjectSerializer;

/**
 * CouponRESTAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CouponRESTAPIApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for countCouponsByCouponCampaign
     *
     * List Coupons.
     *
     */
    public function testCountCouponsByCouponCampaign()
    {
    }

    /**
     * Test case for createCoupon
     *
     * Create Coupon.
     *
     */
    public function testCreateCoupon()
    {
    }

    /**
     * Test case for createCouponPublic
     *
     * Create Coupon (public).
     *
     */
    public function testCreateCouponPublic()
    {
    }

    /**
     * Test case for getCouponByExternalId
     *
     * Get Coupon by External ID.
     *
     */
    public function testGetCouponByExternalId()
    {
    }

    /**
     * Test case for getCouponById
     *
     * Get Coupon by ID.
     *
     */
    public function testGetCouponById()
    {
    }

    /**
     * Test case for listCouponsByCouponCampaign
     *
     * List Coupons.
     *
     */
    public function testListCouponsByCouponCampaign()
    {
    }

    /**
     * Test case for redeemCoupon
     *
     * Redeem Coupon.
     *
     */
    public function testRedeemCoupon()
    {
    }

    /**
     * Test case for updateCoupon
     *
     * Update Coupon.
     *
     */
    public function testUpdateCoupon()
    {
    }

    /**
     * Test case for voidCoupon
     *
     * Void Coupon.
     *
     */
    public function testVoidCoupon()
    {
    }
}
