<?php
/**
 * CouponCampaignRESTAPIApiTest
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Single Use Coupon API
 *
 * This protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 0.1
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace PkIo;

use PkIo\Configuration;
use PkIo\ApiException;
use PkIo\ObjectSerializer;

/**
 * CouponCampaignRESTAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CouponCampaignRESTAPIApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCouponCampaign
     *
     * Create Coupon Campaign.
     *
     */
    public function testCreateCouponCampaign()
    {
    }

    /**
     * Test case for deleteCouponCampaign
     *
     * Delete Coupon Campaign.
     *
     */
    public function testDeleteCouponCampaign()
    {
    }

    /**
     * Test case for getAnalytics
     *
     * Get Coupon Campaign Analytics.
     *
     */
    public function testGetAnalytics()
    {
    }

    /**
     * Test case for getCouponCampaign
     *
     * Get Coupon Campaign.
     *
     */
    public function testGetCouponCampaign()
    {
    }

    /**
     * Test case for listCouponCampaigns
     *
     * List Coupon Campaigns.
     *
     */
    public function testListCouponCampaigns()
    {
    }

    /**
     * Test case for updateCouponCampaign
     *
     * Update Coupon Campaign.
     *
     */
    public function testUpdateCouponCampaign()
    {
    }
}
